name: Semantic Release

concurrency:
  group: "all"
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [ Tests ]
    types:
      - completed

jobs:
  release:
    outputs:
      new-package-versions: ${{ steps.release.outputs.new-versions }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:
      - uses: actions/checkout@v3
      - uses: darksworm/multi-semantic-release@main
        id: release
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          dry-run: false

  trigger-deploy-job:
    needs: [ release ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.release.outputs.new-package-versions) }}
    steps:
      - uses: actions/checkout@v3
      - name: Trigger deploy job for ${{ matrix.package.name }}@${{ matrix.package.version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run "Deploy" -f version=${{ matrix.package.version }} -f package=${{ matrix.package.name }}
